import rigConfig from '@stracker/heft-node-rig/profiles/default/config/eslint.config.mjs';

export default [
  // Generated by `rushx gen` (paraglide-js compile) — never hand-edited, not worth linting.
  { ignores: ['src/paraglide/**'] },
  ...rigConfig
];
